Created landing page
citrushack/citrushack2023 pull request #57
Opened 2023-02-20 07:16 UTC by msclal

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/60799725/220036799-57dbf15f-cc5e-4143-b3bf-b98b8bbe675d.png">

closes issue #21 
@minsooerickim 

- copied svg code from figma to get exact asset layout for landing
- still need to add color and font
- landing page text is in countdown component instead of landing.tsx (dont know if code-wise thats the best practice)

2023-02-20 08:13 UTC, minsooerickim requested changes
landing looks sooo goood 💯

One more comment, instead of creating a component (`landing_asset.tsx`) can you save the SVG file as a .svg file and import it into landing.tsx with a image tag (preferably next/image's Image tag)

2023-02-20 08:13 UTC, minsooerickim commented on components/SignupCounter.tsx
>            <BiEdit className="text-2xl xs:text-3xl" />
you can just get rid the old code here; no need to comment

o also, if u remove the `import { BiEdit } from 'react-icons/bi';` at the top, it'll fix the vercel deployment. ( it's complaining about unused variables)

2023-02-20 08:13 UTC, minsooerickim commented on components/SignupCounter.tsx
> +        {/* <div>
same thing here, i think u can jus remove the old code here

2023-02-20 08:13 UTC, minsooerickim commented on pages/sections/landing.tsx
> +          {/* {!session && (
vercel is also complaining about the `toggleSigninModal` function on line 21.

I think u can just comment out the `toggleSigninModal` function (lines 21-23) to make the vercel deployment pass

2023-02-20 08:25 UTC, minsooerickim commented
> For the text in countdown, ideally, like u said, the text would go in `index.tsx ` and the countdown component would just have the countdown. This stresses the idea of a "component based framework". This way, if we have other places that we need to use the countdown for, we can simply import the countdown as a COMPONENT and use it without having to modify the text or anything.

BUTTT for our case, since we just use the countdown in one place, i think its fine to leave it as is. but its up to u :)))

2023-02-21 00:21 UTC, msclal commented
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/60799725/220214259-111a8fb2-e219-47fa-ad70-3fd90053926b.png">
@minsooerickim 

- colors on buttons, navbar, countdown looks naked and jank
- tried changing colors but realized its not a quick ez-pz lemon squeezy. from what i've gathered, light and dark mode themes are toggled  with ```next-theme``` and ```global.css```. specifically, ```[data-theme='light']``` and ```[data-theme='dark']```  in ```global.css``` are what distinguishes dark/light mode colors. but with mariam's color pallet implementation, global.css is not being used and instead we're using ```tailwind.config.js``` with no separation between light and dark themes. so i think, we need to specify the light and dark mode colors in ```tailwind.config.js``` and make it work with ```next-theme``` 
- also marketing mightve missed some hex colors in the figma. the landing page font colors is not listed
- overall landing page is goooddd it just needs the colors and font. we might need to open another issue to fix the color pallete stuff and offload them to another person so i can get the schedule page going😅  (although i can also do it)

2023-02-21 00:48 UTC, minsooerickim commented
> * mightve missed some hex colors in the fig

yea mariam's hex color changes in `tailwind.config.js` need to be mapped to a variable and the hex codes shud b in `globals.css`. but i just merged it in since i didn't think it was a big deal for now. 

I don't think u have to worry about colors too much rn. I think UIUX and marketing are still messing around with colors in some parts and colors r p ez to fix later on as well so I think ur guudddd.

2023-02-21 00:52 UTC, minsooerickim commented
it seems like the asset doesn't fill the screen on my monitor (1920 x 1080); I remember it looked fine when u had the SVG as a component tho 🤷‍♂️

i think other screen sizes r fine tho. generally, i check for mobile, iPad, laptop, and monitor screen sizes (it seems like ur changes work fine with everything but the monitor size)
![image](https://user-images.githubusercontent.com/62922309/220220818-1189177b-6b1c-4931-aa14-c3d35925250e.png)

2023-02-21 00:53 UTC, minsooerickim commented
> it seems like the asset doesn't fill the screen on my monitor (1920 x 1080); I remember it looked fine when u had the SVG as a component tho 🤷‍♂️
> 
> i think other screen sizes r fine tho. generally, i check for mobile, iPad, laptop, and monitor screen sizes (it seems like ur changes work fine with everything but the monitor size) ![image](https://user-images.githubusercontent.com/62922309/220220818-1189177b-6b1c-4931-aa14-c3d35925250e.png)

ik this can get hella annoying so if it dis is too hard to fix, u can honestly jus revert back to the component method as u did before (i vaguely remember it working on monitor res)

2023-02-21 00:59 UTC, msclal commented
> > it seems like the asset doesn't fill the screen on my monitor (1920 x 1080); I remember it looked fine when u had the SVG as a component tho 🤷‍♂️
> > i think other screen sizes r fine tho. generally, i check for mobile, iPad, laptop, and monitor screen sizes (it seems like ur changes work fine with everything but the monitor size) ![image](https://user-images.githubusercontent.com/62922309/220220818-1189177b-6b1c-4931-aa14-c3d35925250e.png)
> 
> ik this can get hella annoying so if it dis is too hard to fix, u can honestly jus revert back to the component method as u did before (i vaguely remember it working on monitor res)

mmmmm interesting. ill try to make the .svg work if not ill change it back to having it as a component 🫡

2023-02-21 01:31 UTC, msclal commented
<img width="1441" alt="image" src="https://user-images.githubusercontent.com/60799725/220224861-d04bf7df-a301-4979-a606-56a21c6c4ca4.png">

attempt #90139190238 🤞🏼

2023-02-21 04:02 UTC, minsooerickim commented
@msclal ur crackedd 😱😱😱😱😱😱😱😱😱

2023-02-21 04:02 UTC, merged