Team Passports
citrushack/citrushack2023 pull request #90
Opened 2023-03-28 04:18 UTC by bobbyyy57

-- needs to be linked to linkedin

https://user-images.githubusercontent.com/72523111/228121310-60b96615-7e26-4970-9ff1-72953ef91710.mov

2023-03-28 06:47 UTC, minsooerickim requested changes
if you run `yarn format`, it should parse and autoformat your code, and the github actions job called "prettier" will pass and give you a check mark :)))

2023-03-28 06:47 UTC, minsooerickim commented on pages/test.tsx
> +import React from 'react'
I see you made a separate page for testing purposes, but you can directly add the `<Passports />` under `index.tsx` in place of `<Staff/>`
<img width="500" alt="image" src="https://user-images.githubusercontent.com/62922309/228150256-da841b03-6885-4e1a-8467-f11d6fcaa85d.png">

2023-03-28 06:47 UTC, minsooerickim commented on pages/test.tsx
> +import Passports from '@/components/Passports'
when I go to `localhost:3000/test`, I see 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/62922309/228150462-81083e92-ff73-4082-aaf5-973f6dbd3734.png">

it doesn't seem like the pfps flip like the ones you showed me before

2023-03-28 06:47 UTC, minsooerickim commented on public/AladdinIntOS.jpg
you can delete this from ur branch, and commit the deleted file change and it should disappear in this pr

2023-03-28 07:16 UTC, bobbyyy57 commented on public/AladdinIntOS.jpg
@minsooerickim hey minsoo, can you try it out now? i had some issues with pushing my code due to some errors but i was able to push my most recent updates. it is a bit weird that you arent able to see the flips tho. the current  code should be working. let me know how it goes.

2023-03-29 02:00 UTC, minsooerickim commented on public/AladdinIntOS.jpg
ooo yes it works perfectly on my side now. lovin the flippy animations

2023-03-29 02:03 UTC, minsooerickim requested changes
other than this, everything looks ready to be merged in!

2023-03-29 02:03 UTC, minsooerickim commented on pages/index.tsx
> +import Passports from '@/components/Passports.tsx';
vercel is failing deployment because of this import statement right here
should be
```suggestion
import Passports from '@/components/Passports';
```

2023-03-29 07:06 UTC, merged